const gameboard = document.getElementById("wordle-game-board");
const reset = document.getElementById("wordle-reset-button");
const comment = document.getElementById("comment-wordle");
const metaMessage = document.getElementById("meta-message-wordle");
const commentOptions = ["You got this!", "You got this!", "Third time's the charm!", "Fourth time's the charm?", "Do you really know what you're doing?", "Please don't mess this up.", "Tough luck, buddy."];
const rows = Array.from(document.getElementsByClassName("wordle-row"));

// currently adding every 5 letter word in the english language to the game, so that the player can choose from a wide variety of words
// players will be able to enter these, but the actual word to guess will be randomly chosen from a smaller list of common words, so that the game is not too difficult
// this is also the way the new yorks times wordle works, so it is a good way to make the game more authentic
// list source: https://www.wordsdetail.com/5-letter-words/#a
const everyFiveLetterWord = ['aahed', 'aalii', 'aargh', 'abaca', 'abaci', 'aback', 'abaft', 'abaka', 'abamp', 'abase', 'abash', 'abate', 'abaya', 'abbas', 'abbes', 'abbey', 'abbot', 'abeam', 'abele', 'abets', 'abhor', 'abide', 'abled', 'abler', 'ables', 'abmho', 'abode', 'abohm', 'aboil', 'aboma', 'aboon', 'abort', 'about', 'above', 'abris', 'abuse', 'abuts', 'abuzz', 'abyes', 'abysm', 'abyss', 'acari', 'acerb', 'aceta', 'ached', 'aches', 'achoo', 'acids', 'acidy', 'acing', 'acini', 'ackee', 'acmes', 'acmic', 'acned', 'acnes', 'acock', 'acold', 'acorn', 'acred', 'acres', 'acrid', 'acted', 'actin', 'actor', 'acute', 'acyls', 'adage', 'adapt', 'addax', 'added', 'adder', 'addle', 'adeem', 'adept', 'adieu', 'adios', 'adits', 'adman', 'admen', 'admit', 'admix', 'adobe', 'adobo', 'adopt', 'adore', 'adorn', 'adown', 'adoze', 'adult', 'adunc', 'adust', 'adyta', 'adzed', 'adzes', 
    'aecia', 'aedes', 'aegis', 'aeons', 'aerie', 'afars', 'affix', 'afire', 'afoam', 'afoot', 'afore', 'afoul', 'afrit', 'after', 'again', 'agama', 'agape', 'agars', 'agate', 'agave', 'agaze', 'agene', 'agent', 'agers', 'agger', 'aggie', 'aggro', 'aghas', 'agile', 'aging', 'agios', 'agism', 'agist', 'agita', 'aglee', 'aglet', 'agley', 'aglow', 'agmas', 'agone', 'agons', 'agony', 'agora', 'agree', 'agria', 'agues', 'ahead', 'ahing', 'ahold', 'ahull', 'aided', 'aider', 'aides', 'ailed', 'aimed', 'aimer', 'aioli', 'aired', 'airer', 'airns', 'airth', 'airts', 'aisle', 'aitch', 'aiver', 'ajiva', 'ajuga', 'akees', 'akela', 'akene', 'alack', 'alamo', 'aland', 'alane', 'alang', 'alans', 'alant', 'alarm', 'alary', 'alate', 'albas', 'album', 'alcid', 'alder', 'aldol', 'alecs', 'alefs', 'aleph', 'alert', 'alfas', 'algae', 'algal', 'algas', 'algid', 'algin', 'algor', 'algum', 'alias', 
    'alibi', 'alien', 'alifs', 'align', 'alike', 'aline', 'alist', 'alive', 'aliya', 'alkie', 'alkyd', 'alkyl', 'allay', 'allee', 'alley', 'allod', 'allot', 'allow', 'alloy', 'allyl', 'almah', 'almas', 'almeh', 'almes', 'almud', 'almug', 'aloes', 'aloft', 'aloha', 'aloin', 'alone', 'along', 'aloof', 'aloud', 'alpha', 'altar', 'alter', 'altho', 'altos', 'alula', 'alums', 'alure', 'alway', 'amahs', 'amain', 'amass', 'amaze', 'amber', 'ambit', 'amble', 'ambos', 'ambry', 'ameba', 'ameer', 'amend', 'amens', 'ament', 'amias', 'amice', 'amici', 'amide', 'amido', 'amids', 'amies', 'amiga', 'amigo', 'amine', 'amino', 'amins', 'amirs', 'amiss', 'amity', 'ammos', 'amnia', 'amnic', 'amnio', 'amoks', 'amole', 'among', 'amort', 'amour', 'amped', 'ample', 'amply', 'ampul', 'amuck', 'amuse', 'amyls', 'ancho', 'ancon', 'andro', 'anear', 'anele', 'anent', 'angas', 'angel', 'anger', 'angle', 
    'anglo', 'angry', 'angst', 'anile', 'anils', 'anima', 'anime', 'animi', 'anion', 'anise', 'ankhs', 'ankle', 'ankus', 'anlas', 'annal', 'annas', 'annex', 'annoy', 'annul', 'anoas', 'anode', 'anole', 'anomy', 'ansae', 'antae', 'antas', 'anted', 'antes', 'antic', 'antis', 'antra', 'antre', 'antsy', 'anvil', 'anyon', 'aorta', 'apace', 'apart', 'apeak', 'apeek', 'apers', 'apery', 'aphid', 'aphis', 'apian', 'aping', 'apish', 'apnea', 'apods', 'aport', 'appal', 'appel', 'apple', 'apply', 'apres', 'apron', 'apses', 'apsis', 'apter', 'aptly', 'aquae', 'aquas', 'araks', 'arame', 'arbor', 'arced', 'arcus', 'ardeb', 'ardor', 'areae', 'areal', 'areas', 'areca', 'areic', 'arena', 'arene', 'arepa', 'arete', 'argal', 'argil', 'argle', 'argol', 'argon', 'argot', 'argue', 'argus', 'arhat', 'arias', 'ariel', 'arils', 'arise', 'arles', 'armed', 'armer', 'armet', 'armor', 'aroid', 'aroma', 
    'arose', 'arpen', 'arras', 'array', 'arris', 'arrow', 'arses', 'arsis', 'arson', 'artal', 'artel', 'artsy', 'arums', 'arval', 'arvos', 'aryls', 'asana', 'ascot', 'ascus', 'asdic', 'ashed', 'ashen', 'ashes', 'aside', 'asked', 'asker', 'askew', 'askoi', 'askos', 'aspen', 'asper', 'aspic', 'aspis', 'assai', 'assay', 'asset', 'aster', 'astir', 'asyla', 'ataps', 'ataxy', 'atilt', 'atlas', 'atman', 'atmas', 'atoll', 'atoms', 'atomy', 'atone', 'atony', 'atopy', 'atria', 'atrip', 'attar', 'attic', 'audad', 'audio', 'audit', 'auger', 'aught', 'augur', 'aulic', 'aunts', 'aunty', 'aurae', 'aural', 'aurar', 'auras', 'aurei', 'aures', 'auric', 'auris', 'aurum', 'autos', 'auxin', 'avail', 'avant', 'avast', 'avens', 'avers', 'avert', 'avgas', 'avian', 'avion', 'aviso', 'avoid', 'avows', 'await', 'awake', 'award', 'aware', 'awash', 'awful', 'awing', 'awned', 'awoke', 'awols', 'axels', 
    'axial', 'axile', 'axils', 'axing', 'axiom', 'axion', 'axite', 'axled', 'axles', 'axman', 'axmen', 'axone', 'axons', 'ayahs', 'ayins', 'azans', 'azide', 'azido', 'azine', 'azlon', 'azoic', 'azole', 'azons', 'azote', 'azoth', 'azuki', 'azure', 
    
    'baaed', 'baals', 'babas', 'babel', 'babes', 'babka', 'baboo', 'babul', 'babus', 'bacca', 'backs', 'bacon', 'baddy', 'badge', 'badly', 'baffs', 'baffy', 'bagel', 'baggy', 'bahts', 'bails', 'bairn', 'baith', 'baits', 'baiza', 'baize', 'baked', 'baker', 'bakes', 'balas', 'balds', 'baldy', 'baled', 'baler', 'bales', 'balks', 'balky', 'bally', 'balms', 'balmy', 'balsa', 'banal', 'banco', 'banda', 'bands', 'bandy', 'baned', 'banes', 'bangs', 'banjo', 'banks', 'banns', 'banty', 'barbe', 'barbs', 'barca', 'barde', 'bards', 'bared', 'barer', 'bares', 'barfs', 'barge', 'baric', 'barks', 'barky', 'barms', 'barmy', 'barns', 'barny', 'baron', 'barre', 'barye', 'basal', 'based', 'baser', 'bases', 'basic', 'basil', 'basin', 'basis', 'basks', 'bassi', 'basso', 'bassy', 'baste', 'basts', 'batch', 'bated', 'bates', 'bathe', 'baths', 'batik', 'baton', 'batts', 'battu', 'batty', 'bauds', 
    'baulk', 'bawds', 'bawdy', 'bawls', 'bawty', 'bayed', 'bayou', 'bazar', 'bazoo', 'beach', 'beads', 'beady', 'beaks', 'beaky', 'beams', 'beamy', 'beano', 'beans', 'beard', 'bears', 'beast', 'beats', 'beaus', 'beaut', 'beaux', 'bebop', 'becap', 'becks', 'bedel', 'bedew', 'bedim', 'beech', 'beedi', 'beefs', 'beefy', 'beeps', 'beers', 'beery', 'beets', 'befit', 'befog', 'began', 'begat', 'beget', 'begin', 'begot', 'begum', 'begun', 'beige', 'beigy', 'being', 'belay', 'belch', 'belga', 'belie', 'belle', 'bells', 'belly', 'belon', 'below', 'belts', 'bemas', 'bemix', 'bench', 'bends', 'bendy', 'benes', 'benne', 'benni', 'benny', 'bento', 'bents', 'beret', 'bergs', 'berks', 'berme', 'berms', 'berry', 'berth', 'beryl', 'beses', 'beset', 'besom', 'besot', 'bests', 'betas', 'betel', 'beths', 'beton', 'betta', 'bevel', 'bevor', 'bewig', 'bezel', 'bezil', 'bhang', 'bhoot', 'bhuts', 
    'biali', 'bialy', 'bibbs', 'bible', 'bicep', 'bices', 'biddy', 'bided', 'bider', 'bides', 'bidet', 'bidis', 'bield', 'biers', 'biffs', 'biffy', 'bifid', 'biggy', 'bight', 'bigly', 'bigos', 'bigot', 'bijou', 'biked', 'biker', 'bikes', 'bikie', 'bilbo', 'bilby', 'biles', 'bilge', 'bilgy', 'bilks', 'bills', 'billy', 'bimah', 'bimas', 'bimbo', 'binal', 'bindi', 'binds', 'biner', 'bines', 'binge', 'bingo', 'binit', 'bints', 'biogs', 'biome', 'biont', 'biota', 'biped', 'bipod', 'birch', 'birds', 'birdy', 'birks', 'birle', 'birls', 'biros', 'birrs', 'birse', 'birth', 'bises', 'bisks', 'bison', 'biter', 'bites', 'bitsy', 'bitts', 'bitty', 'bizes', 'blabs', 'black', 'blade', 'blaff', 'blahs', 'blain', 'blame', 'blams', 'bland', 'blank', 'blare', 'blase', 'blast', 'blate', 'blats', 'blawn', 'blaws', 'blaze', 'bleak', 'blear', 'bleat', 'blebs', 'bleed', 'bleep', 'blend', 'blent', 
    'bless', 'blest', 'blets', 'blimp', 'blimy', 'blind', 'bling', 'blini', 'blink', 'blips', 'bliss', 'blite', 'blitz', 'bloat', 'blobs', 'block', 'blocs', 'blogs', 'bloke', 'blond', 'blood', 'bloom', 'bloop', 'blots', 'blown', 'blows', 'blowy', 'blubs', 'blued', 'bluer', 'blues', 'bluet', 'bluey', 'bluff', 'blume', 'blunt', 'blurb', 'blurs', 'blurt', 'blush', 'blype', 'board', 'boars', 'boart', 'boast', 'boats', 'bobby', 'bocce', 'bocci', 'boche', 'bocks', 'boded', 'bodes', 'boffo', 'boffs', 'bogan', 'bogey', 'boggy', 'bogie', 'bogle', 'bogus', 'bohea', 'bohos', 'boils', 'boing', 'boink', 'boite', 'bokeh', 'bolar', 'bolas', 'bolds', 'boles', 'bolls', 'bolos', 'bolts', 'bolus', 'bombe', 'bombs', 'bonds', 'boned', 'bones', 'boney', 'bongo', 'bongs', 'bonks', 'bonne', 'bonny', 'bonus', 'bonze', 'booby', 'boody', 'booed', 'boogy', 'books', 'booms', 'boomy', 'boons', 'boors', 
    'boost', 'booth', 'boots', 'booty', 'booze', 'boozy', 'boral', 'boras', 'borax', 'bored', 'borer', 'bores', 'boric', 'borks', 'borne', 'boron', 'borts', 'borty', 'bortz', 'bosks', 'bosky', 'bosom', 'boson', 'bossy', 'bosun', 'botas', 'botch', 'botel', 'bothy', 'botts', 'bough', 'boule', 'bound', 'bourg', 'bourn', 'bouse', 'bousy', 'bouts', 'bovid', 'bowed', 'bowel', 'bower', 'bowls', 'bowse', 'boxed', 'boxer', 'boxes', 'boyar', 'boyla', 'boyos', 'bozos', 'brace', 'brach', 'bract', 'brads', 'braes', 'brags', 'braid', 'brail', 'brain', 'brake', 'braky', 'brand', 'brank', 'brans', 'brant', 'brash', 'brass', 'brats', 'brava', 'brave', 'bravi', 'bravo', 'brawl', 'brawn', 'braws', 'braxy', 'brays', 'braza', 'braze', 'bread', 'break', 'bream', 'brede', 'breed', 'brees', 'brens', 'brent', 'breve', 'brews', 'briar', 'bribe', 'brick', 'bride', 'brief', 'brier', 'bries', 'brigs', 
    'brill', 'brims', 'brine', 'bring', 'brink', 'brins', 'briny', 'brios', 'brisk', 'briss', 'brith', 'brits', 'britt', 'broad', 'brock', 'broil', 'broke', 'brome', 'bromo', 'bronc', 'brood', 'brook', 'broom', 'broos', 'brose', 'brosy', 'broth', 'brown', 'brows', 'brugh', 'bruin', 'bruit', 'brume', 'brung', 'brunt', 'brush', 'brusk', 'brute', 'bruts', 'bubal', 'bubba', 'bubby', 'bubus', 'bucko', 'bucks', 'buddy', 'budge', 'buffi', 'buffo', 'buffs', 'buffy', 'buggy', 'bugle', 'buhls', 'buhrs', 'build', 'built', 'bulbs', 'bulge', 'bulgy', 'bulks', 'bulky', 'bulla', 'bulls', 'bully', 'bumfs', 'bumph', 'bumps', 'bumpy', 'bunas', 'bunch', 'bunco', 'bunds', 'bundt', 'bungs', 'bunko', 'bunks', 'bunns', 'bunny', 'bunts', 'bunya', 'buoys', 'buppy', 'buran', 'buras', 'burbs', 'burds', 'buret', 'burgh', 'burgs', 'burin', 'burka', 'burke', 'burls', 'burly', 'burns', 'burnt', 'burps', 
    'burqa', 'burro', 'burrs', 'burry', 'bursa', 'burse', 'burst', 'busby', 'bused', 'buses', 'bushy', 'busks', 'busts', 'busty', 'butch', 'buteo', 'butes', 'butle', 'butte', 'butts', 'butty', 'butut', 'butyl', 'buxom', 'buyer', 'bwana', 'bylaw', 'byres', 'byrls', 'byssi', 'bytes', 'byway',

    'cabal', 'cabby', 'caber', 'cabin', 'cable', 'cabob', 'cacao', 'cacas', 'cache', 'cacti', 'caddy', 'cades', 'cadet', 'cadge', 'cadgy', 'cadis', 'cadre', 'caeca', 'cafes', 'caffs', 'caged', 'cager', 'cages', 'cagey', 'cahow', 'caids', 'cains', 'caird', 'cairn', 'cajon', 'caked', 'cakes', 'cakey', 'calfs', 'calif', 'calix', 'calks', 'calla', 'calls', 'calms', 'calos', 'calve', 'calyx', 'camas', 'camel', 'cameo', 'cames', 'camos', 'campi', 'campo', 'camps', 'campy', 'canal', 'candy', 'caned', 'caner', 'canes', 'canid', 'canna', 'canny', 'canoe', 'canon', 'canso', 'canst', 'canto', 'cants', 'canty', 'caped', 'caper', 'capes', 'caphs', 'capiz', 'capon', 'capos', 'caput', 'carat', 'carbo', 'carbs', 'cards', 'cared', 'carer', 'cares', 'caret', 'carex', 'cargo', 'carks', 'carle', 'carls', 'carns', 'carny', 'carob', 'carol', 'carom', 'carpi', 'carps', 'carrs', 'carry', 'carse', 
    'carte', 'carts', 'carve', 'casas', 'cased', 'cases', 'casks', 'casky', 'caste', 'casts', 'casus', 'catch', 'cater', 'cates', 'catty', 'cauld', 'caulk', 'cauls', 'cause', 'caved', 'caver', 'caves', 'cavie', 'cavil', 'cawed', 'cease', 'cebid', 'cecal', 'cecum', 'cedar', 'ceded', 'ceder', 'cedes', 'cedis', 'ceiba', 'ceili', 'ceils', 'celeb', 'cella', 'celli', 'cello', 'cells', 'celom', 'celts', 'cense', 'cento', 'cents', 'centu', 'ceorl', 'cepes', 'cerci', 'cered', 'ceres', 'ceria', 'ceric', 'ceros', 'cesta', 'cesti', 'cetes', 'chads', 'chafe', 'chaff', 'chain', 'chair', 'chais', 'chalk', 'champ', 'chams', 'chang', 'chant', 'chaos', 'chape', 'chaps', 'chapt', 'chard', 'chare', 'chark', 'charm', 'charr', 'chars', 'chart', 'chary', 'chase', 'chasm', 'chats', 'chaws', 'chays', 'cheap', 'cheat', 'check', 'cheek', 'cheep', 'cheer', 'chefs', 'chela', 'chemo', 'chert', 'chess', 
    'chest', 'cheth', 'chevy', 'chews', 'chewy', 'chiao', 'chias', 'chica', 'chick', 'chico', 'chics', 'chide', 'chief', 'chiel', 'child', 'chile', 'chili', 'chill', 'chimb', 'chime', 'chimp', 'china', 'chine', 'chino', 'chins', 'chips', 'chirk', 'chirm', 'chiro', 'chirp', 'chirr', 'chiru', 'chits', 'chive', 'chivy', 'chock', 'chode', 'choir', 'choke', 'choky', 'chola', 'chomp', 'chook', 'chops', 'chord', 'chore', 'chose', 'chott', 'chows', 'chubs', 'chuck', 'chufa', 'chuff', 'chugs', 'chump', 'chums', 'chunk', 'churl', 'churn', 'churr', 'chute', 'chyle', 'chyme', 'cibol', 'cider', 'cigar', 'cilia', 'cimex', 'cinch', 'cines', 'cions', 'circa', 'cires', 'cirri', 'cisco', 'cissy', 'cists', 'cited', 'citer', 'cites', 'civet', 'civic', 'civie', 'civil', 'civvy', 'clach', 'clack', 'clade', 'clads', 'clags', 'claim', 'clamp', 'clams', 'clang', 'clank', 'clans', 'claps', 'clapt', 
    'claro', 'clary', 'clash', 'clasp', 'class', 'clast', 'clave', 'clavi', 'claws', 'clays', 'clean', 'clear', 'cleat', 'cleek', 'clefs', 'cleft', 'clepe', 'clept', 'clerk', 'clews', 'click', 'cliff', 'clift', 'climb', 'clime', 'cline', 'cling', 'clink', 'clips', 'clipt', 'cloak', 'clock', 'clods', 'clogs', 'clomb', 'clomp', 'clone', 'clonk', 'clons', 'cloot', 'clops', 'close', 'cloth', 'clots', 'cloud', 'clour', 'clout', 'clove', 'clown', 'cloys', 'cloze', 'clubs', 'cluck', 'clued', 'clues', 'clump', 'clung', 'clunk', 'cnida', 'coach', 'coact', 'coala', 'coals', 'coaly', 'coapt', 'coast', 'coati', 'coats', 'cobbs', 'cobby', 'cobia', 'coble', 'cobra', 'cocas', 'cocci', 'cocky', 'cocoa', 'cocos', 'codas', 'codec', 'coded', 'coden', 'coder', 'codes', 'codex', 'codon', 'coeds', 'coffs', 'cogon', 'cohog', 'cohos', 'coifs', 'coign', 'coils', 'coins', 'coirs', 'coked', 'cokes', 
    'colas', 'colby', 'colds', 'coled', 'coles', 'colic', 'colin', 'colly', 'colog', 'colon', 'color', 'colts', 'colza', 'comae', 'comal', 'comas', 'combe', 'combo', 'combs', 'comer', 'comes', 'comet', 'comfy', 'comic', 'comix', 'comma', 'commy', 'compo', 'comps', 'compt', 'comte', 'conch', 'condo', 'coned', 'cones', 'coney', 'conga', 'conge', 'congo', 'conic', 'conin', 'conks', 'conky', 'conns', 'conte', 'conto', 'conus', 'cooch', 'cooed', 'cooee', 'cooer', 'cooey', 'coofs', 'cooks', 'cooky', 'cools', 'cooly', 'coomb', 'coons', 'coops', 'coopt', 'coots', 'copal', 'copay', 'coped', 'copen', 'coper', 'copes', 'copra', 'copse', 'coral', 'corby', 'cords', 'cored', 'corer', 'cores', 'corgi', 'coria', 'corks', 'corky', 'corms', 'corns', 'cornu', 'corny', 'corps', 'corse', 'cosec', 'coses', 'coset', 'cosey', 'cosie', 'costa', 'costs', 'cotan', 'coted', 'cotes', 'cotta', 'couch', 
    'coude', 'cough', 'could', 'count', 'coupe', 'coups', 'court', 'couth', 'coved', 'coven', 'cover', 'coves', 'covet', 'covey', 'covin', 'cowed', 'cower', 'cowls', 'cowry', 'coxae', 'coxal', 'coxed', 'coxes', 'coyed', 'coyer', 'coyly', 'coypu', 'cozen', 'cozes', 'cozey', 'cozie', 'craal', 'crabs', 'crack', 'craft', 'crags', 'crake', 'cramp', 'crams', 'crane', 'crank', 'crape', 'craps', 'crash', 'crass', 'crate', 'crave', 'crawl', 'craws', 'craze', 'crazy', 'creak', 'cream', 'credo', 'creds', 'creed', 'creek', 'creel', 'creep', 'creme', 'crepe', 'crept', 'crepy', 'cress', 'crest', 'crews', 'cribs', 'crick', 'cried', 'crier', 'cries', 'crime', 'crimp', 'cripe', 'crisp', 'crits', 'croak', 'croci', 'crock', 'crocs', 'croft', 'crone', 'crony', 'crook', 'croon', 'crops', 'crore', 'cross', 'croup', 'crowd', 'crown', 'crows', 'croze', 'cruck', 'crude', 'cruds', 'cruel', 'cruet', 
    'crumb', 'crump', 'cruor', 'crura', 'cruse', 'crush', 'crust', 'crwth', 'crypt', 'cubby', 'cubeb', 'cubed', 'cuber', 'cubes', 'cubic', 'cubit', 'cuddy', 'cuffs', 'cuifs', 'cuing', 'cuish', 'cukes', 'culch', 'culet', 'culex', 'culls', 'cully', 'culms', 'culpa', 'culti', 'cults', 'cumin', 'cupel', 'cupid', 'cuppa', 'cuppy', 'curbs', 'curch', 'curds', 'curdy', 'cured', 'curer', 'cures', 'curet', 'curfs', 'curia', 'curie', 'curio', 'curls', 'curly', 'curns', 'currs', 'curry', 'curse', 'curst', 'curve', 'curvy', 'cusec', 'cushy', 'cusks', 'cusps', 'cusso', 'cutch', 'cuter', 'cutes', 'cutey', 'cutie', 'cutin', 'cutis', 'cutty', 'cutup', 'cuvee', 'cyano', 'cyans', 'cyber', 'cycad', 'cycas', 'cycle', 'cyclo', 'cyder', 'cylix', 'cymae', 'cymar', 'cymas', 'cymes', 'cymol', 'cynic', 'cysts', 'cyton', 'czars',

    'daces', 'dacha', 'dadas', 'daddy', 'dados', 'daffs', 'daffy', 'dagga', 'dahls', 'daily', 'dairy', 'daisy', 'dales', 'dally', 'daman', 'damar', 'dames', 'damns', 'damps', 'dance', 'dandy', 'dangs', 'danio', 'darbs', 'dared', 'darer', 'dares', 'daric', 'darks', 'darns', 'darts', 'dashi', 'dashy', 'dated', 'dater', 'dates', 'datos', 'datto', 'datum', 'daube', 'daubs', 'dauby', 'daunt', 'dauts', 'daven', 'davit', 'dawed', 'dawen', 'dawks', 'dawns', 'dawts', 'dazed', 'dazes', 'deads', 'deair', 'deals', 'dealt', 'deans', 'dears', 'deary', 'deash', 'death', 'deave', 'debag', 'debar', 'debit', 'debts', 'debug', 'debut', 'debye', 'decaf', 'decal', 'decay', 'decks', 'decor', 'decos', 'decoy', 'decry', 'dedal', 'deeds', 'deedy', 'deems', 'deeps', 'deers', 'deets', 'defat', 'defer', 'defis', 'defog', 'degas', 'degum', 'deice', 'deify', 'deign', 'deils', 'deism', 'deist', 'deity', 
    'deked', 'dekes', 'dekko', 'delay', 'deled', 'deles', 'delfs', 'delft', 'delis', 'dells', 'delly', 'delta', 'delts', 'delve', 'demes', 'demic', 'demit', 'demob', 'demon', 'demos', 'demur', 'denar', 'denes', 'denim', 'dense', 'dents', 'deoxy', 'depot', 'depth', 'derat', 'deray', 'derby', 'derma', 'derms', 'derry', 'desex', 'desks', 'deter', 'detox', 'deuce', 'devas', 'devel', 'devil', 'devon', 'dewan', 'dewar', 'dewax', 'dewed', 'dexes', 'dexie', 'dhaks', 'dhals', 'dhobi', 'dhole', 'dhoti', 'dhows', 'dhuti', 'dials', 'diary', 'diazo', 'diced', 'dicer', 'dices', 'dicey', 'dicky', 'dicot', 'dicta', 'dicty', 'didie', 'didos', 'didst', 'diene', 'diets', 'diffs', 'dight', 'digit', 'diked', 'diker', 'dikes', 'dikey', 'dills', 'dilly', 'dimer', 'dimes', 'dimly', 'dinar', 'dined', 'diner', 'dines', 'dinge', 'dingo', 'dings', 'dingy', 'dinky', 'dinos', 'dints', 'diode', 'diols', 
    'dippy', 'dipso', 'diram', 'direr', 'dirge', 'dirks', 'dirls', 'dirts', 'dirty', 'disci', 'disco', 'discs', 'dishy', 'disks', 'disme', 'ditas', 'ditch', 'dites', 'ditsy', 'ditto', 'ditty', 'ditzy', 'divan', 'divas', 'dived', 'diver', 'dives', 'divot', 'divvy', 'diwan', 'dixie', 'dixit', 'dizen', 'dizzy', 'djinn', 'djins', 'doats', 'dobby', 'dobie', 'dobla', 'dobra', 'dobro', 'docks', 'dodge', 'dodgy', 'dodos', 'doers', 'doest', 'doeth', 'doffs', 'doges', 'dogey', 'doggo', 'doggy', 'dogie', 'dogma', 'doily', 'doing', 'doits', 'dojos', 'dolce', 'dolci', 'doled', 'doles', 'dolls', 'dolly', 'dolma', 'dolor', 'dolts', 'domal', 'domed', 'domes', 'domic', 'donas', 'donee', 'donga', 'dongs', 'donna', 'donne', 'donor', 'donsy', 'donut', 'doody', 'dooly', 'dooms', 'doomy', 'doors', 'doozy', 'dopas', 'doped', 'doper', 'dopes', 'dopey', 'dorks', 'dorky', 'dorms', 'dormy', 'dorps', 
    'dorrs', 'dorsa', 'dorty', 'dosed', 'doser', 'doses', 'dotal', 'doted', 'doter', 'dotes', 'dotty', 'doubt', 'douce', 'dough', 'doula', 'douma', 'doums', 'doura', 'douse', 'doven', 'doves', 'dowdy', 'dowed', 'dowel', 'dower', 'dowie', 'downs', 'downy', 'dowry', 'dowse', 'doxie', 'doyen', 'doyly', 'dozed', 'dozen', 'dozer', 'dozes', 'drabs', 'draff', 'draft', 'drags', 'drail', 'drain', 'drake', 'drama', 'drams', 'drank', 'drape', 'drats', 'drave', 'drawl', 'drawn', 'draws', 'drays', 'dread', 'dream', 'drear', 'dreck', 'dreed', 'drees', 'dregs', 'dreks', 'dress', 'drest', 'dribs', 'dried', 'drier', 'dries', 'drift', 'drill', 'drily', 'drink', 'drips', 'dript', 'drive', 'droid', 'droit', 'droll', 'drone', 'drool', 'droop', 'drops', 'dropt', 'dross', 'drouk', 'drove', 'drown', 'drubs', 'drugs', 'druid', 'drums', 'drunk', 'drupe', 'druse', 'dryad', 'dryer', 'dryly', 'duads', 
    'duals', 'ducal', 'ducat', 'duces', 'duchy', 'ducks', 'ducky', 'ducts', 'duddy', 'duded', 'dudes', 'duels', 'duets', 'duffs', 'dufus', 'duits', 'duked', 'dukes', 'dulia', 'dulls', 'dully', 'dulse', 'dumas', 'dumbo', 'dumbs', 'dumka', 'dumky', 'dummy', 'dumps', 'dumpy', 'dunam', 'dunce', 'dunch', 'dunes', 'dungs', 'dungy', 'dunks', 'dunts', 'duomi', 'duomo', 'duped', 'duper', 'dupes', 'duple', 'dural', 'duras', 'dured', 'dures', 'durns', 'duroc', 'duros', 'durra', 'durrs', 'durst', 'durum', 'dusks', 'dusky', 'dusts', 'dusty', 'dutch', 'duvet', 'dwarf', 'dweeb', 'dwell', 'dwelt', 'dwine', 'dyads', 'dyers', 'dying', 'dyked', 'dykes', 'dykey', 'dynel', 'dynes',

    'eager', 'eagle', 'eagre', 'eared', 'earls', 'early', 'earns', 'earth', 'eased', 'easel', 'eases', 'easts', 'eaten', 'eater', 'eaved', 'eaves', 'ebbed', 'ebbet', 'ebola', 'ebons', 'ebony', 'ebook', 'eched', 'eches', 'echos', 'eclat', 'ecrus', 'edema', 'edged', 'edger', 'edges', 'edict', 'edify', 'edile', 'edits', 'educe', 'educt', 'eerie', 'egads', 'egers', 'egest', 'eggar', 'egged', 'egger', 'egret', 'eider', 'eidos', 'eight', 'eikon', 'eject', 'eking', 'elain', 'eland', 'elans', 'elate', 'elbow', 'elder', 'elect', 'elegy', 'elemi', 'elfin', 'elide', 'elint', 'elite', 'eloin', 'elope', 'elude', 'elute', 'elver', 'elves', 'email', 'embar', 'embay', 'embed', 'ember', 'embow', 'emcee', 'emeer', 'emend', 'emery', 'emeus', 'emirs', 'emits', 'emmer', 'emmet', 'emmys', 'emote', 'empty', 'emyde', 'emyds', 'enact', 'enate', 'ended', 'ender', 'endow', 'endue', 'enema', 'enemy', 
    'enjoy', 'ennui', 'enoki', 'enols', 'enorm', 'enows', 'enrol', 'ensky', 'ensue', 'enter', 'entia', 'entry', 'enure', 'envoi', 'envoy', 'enzym', 'eosin', 'epact', 'epees', 'ephah', 'ephas', 'ephod', 'ephor', 'epics', 'epoch', 'epode', 'epoxy', 'equal', 'equid', 'equip', 'erase', 'erect', 'ergot', 'erica', 'ernes', 'erode', 'erose', 'erred', 'error', 'erses', 'eruct', 'erugo', 'erupt', 'ervil', 'escar', 'escot', 'eskar', 'esker', 'esnes', 'essay', 'esses', 'ester', 'estop', 'etape', 'ether', 'ethic', 'ethos', 'ethyl', 'etnas', 'etude', 'etuis', 'etwee', 'etyma', 'euros', 'evade', 'evens', 'event', 'evert', 'every', 'evict', 'evils', 'evite', 'evoke', 'ewers', 'exact', 'exalt', 'exams', 'excel', 'execs', 'exert', 'exile', 'exine', 'exing', 'exist', 'exits', 'exons', 'expat', 'expel', 'expos', 'extol', 'extra', 'exude', 'exult', 'exurb', 'eyass', 'eyers', 'eying', 'eyras', 
    'eyres', 'eyrie', 'eyrir',

    'fable', 'faced', 'facer', 'faces', 'facet', 'facia', 'facts', 'faddy', 'faded', 'fader', 'fades', 'fadge', 'fados', 'faena', 'faery', 'faggy', 'fagin', 'fails', 'faint', 'fairs', 'fairy', 'faith', 'faked', 'faker', 'fakes', 'fakey', 'fakir', 'falls', 'false', 'famed', 'fames', 'fancy', 'fanes', 'fanga', 'fangs', 'fanon', 'fanos', 'fanum', 'faqir', 'farad', 'farce', 'farci', 'farcy', 'fards', 'fared', 'farer', 'fares', 'farle', 'farls', 'farms', 'faros', 'farts', 'fasts', 'fatal', 'fated', 'fates', 'fatly', 'fatso', 'fatty', 'fatwa', 'faugh', 'fauld', 'fault', 'fauna', 'fauns', 'fauve', 'favas', 'faves', 'favor', 'favus', 'fawns', 'fawny', 'faxed', 'faxes', 'fayed', 'fazed', 'fazes', 'fears', 'fease', 'feast', 'feats', 'feaze', 'fecal', 'feces', 'fecks', 'fedex', 'feebs', 'feeds', 'feels', 'feeze', 'feign', 'feint', 'feist', 'felid', 'fella', 'fells', 'felly', 'felon', 
    'felts', 'femes', 'femme', 'femur', 'fence', 'fends', 'fenny', 'feods', 'feoff', 'feral', 'feres', 'feria', 'ferly', 'fermi', 'ferns', 'ferny', 'ferry', 'fesse', 'fests', 'fetal', 'fetas', 'fetch', 'feted', 'fetes', 'fetid', 'fetor', 'fetus', 'feuar', 'feuds', 'feued', 'fever', 'fewer', 'feyer', 'feyly', 'fezes', 'fezzy', 'fiars', 'fiats', 'fiber', 'fibre', 'fices', 'fiche', 'fichu', 'ficin', 'ficus', 'fidge', 'fidos', 'fiefs', 'field', 'fiend', 'fiery', 'fifed', 'fifer', 'fifes', 'fifth', 'fifty', 'fight', 'filar', 'filch', 'filed', 'filer', 'files', 'filet', 'fille', 'fillo', 'fills', 'filly', 'filmi', 'films', 'filmy', 'filos', 'filth', 'filum', 'final', 'finca', 'finch', 'finds', 'fined', 'finer', 'fines', 'finis', 'finks', 'finny', 'finos', 'fiord', 'fique', 'fired', 'firer', 'fires', 'firms', 'firns', 'firry', 'first', 'firth', 'fiscs', 'fishy', 'fists', 'fitch', 
    'fitly', 'fiver', 'fives', 'fixed', 'fixer', 'fixes', 'fixit', 'fizzy', 'fjeld', 'fjord', 'flabs', 'flack', 'flags', 'flail', 'flair', 'flake', 'flaky', 'flame', 'flams', 'flamy', 'flank', 'flans', 'flaps', 'flare', 'flash', 'flask', 'flats', 'flaws', 'flawy', 'flaxy', 'flays', 'fleam', 'fleas', 'fleck', 'fleer', 'flees', 'fleet', 'flesh', 'flews', 'fleys', 'flick', 'flics', 'flied', 'flier', 'flies', 'fling', 'flint', 'flips', 'flirs', 'flirt', 'flite', 'flits', 'float', 'flock', 'flocs', 'floes', 'flogs', 'flong', 'flood', 'floor', 'flops', 'flora', 'floss', 'flota', 'flour', 'flout', 'flown', 'flows', 'flubs', 'flued', 'flues', 'fluff', 'fluid', 'fluke', 'fluky', 'flume', 'flump', 'flung', 'flunk', 'fluor', 'flush', 'flute', 'fluty', 'fluyt', 'flyby', 'flyer', 'flyte', 'foals', 'foams', 'foamy', 'focal', 'focus', 'foehn', 'fogey', 'foggy', 'fogie', 'fohns', 'foils', 
    'foins', 'foist', 'folds', 'foley', 'folia', 'folic', 'folio', 'folks', 'folky', 'folly', 'fonds', 'fondu', 'fonts', 'foods', 'fools', 'foots', 'footy', 'foram', 'foray', 'forbs', 'forby', 'force', 'fordo', 'fords', 'fores', 'forge', 'forgo', 'forks', 'forky', 'forme', 'forms', 'forte', 'forth', 'forts', 'forty', 'forum', 'fossa', 'fosse', 'fouls', 'found', 'fount', 'fours', 'fovea', 'fowls', 'foxed', 'foxes', 'foyer', 'frags', 'frail', 'frame', 'franc', 'frank', 'fraps', 'frass', 'frats', 'fraud', 'frays', 'freak', 'freed', 'freer', 'frees', 'fremd', 'frena', 'frere', 'fresh', 'frets', 'friar', 'fried', 'frier', 'fries', 'frigs', 'frill', 'frise', 'frisk', 'frith', 'frits', 'fritt', 'fritz', 'frizz', 'frock', 'froes', 'frogs', 'frond', 'frons', 'front', 'frore', 'frosh', 'frost', 'froth', 'frown', 'frows', 'froze', 'frugs', 'fruit', 'frump', 'fryer', 'fubar', 'fubsy', 
    'fucus', 'fuddy', 'fudge', 'fuels', 'fugal', 'fuggy', 'fugio', 'fugle', 'fugue', 'fugus', 'fujis', 'fulls', 'fully', 'fumed', 'fumer', 'fumes', 'fumet', 'fundi', 'funds', 'fungi', 'fungo', 'funks', 'funky', 'funny', 'furan', 'furls', 'furor', 'furry', 'furze', 'furzy', 'fused', 'fusee', 'fusel', 'fuses', 'fusil', 'fussy', 'fusty', 'futon', 'fuzed', 'fuzee', 'fuzes', 'fuzil', 'fuzzy', 'fyces', 'fykes', 'fytte',

    'gabby', 'gable', 'gaddi', 'gadid', 'gadis', 'gadje', 'gadjo', 'gaffe', 'gaffs', 'gaged', 'gager', 'gages', 'gaily', 'gains', 'gaits', 'galah', 'galas', 'galax', 'galea', 'gales', 'galls', 'gally', 'galop', 'gamas', 'gamay', 'gamba', 'gambe', 'gambs', 'gamed', 'gamer', 'games', 'gamey', 'gamic', 'gamin', 'gamma', 'gammy', 'gamps', 'gamut', 'ganef', 'ganev', 'gangs', 'ganja', 'ganof', 'gaols', 'gaped', 'gaper', 'gapes', 'gappy', 'garbs', 'garda', 'garni', 'garth', 'gases', 'gasps', 'gassy', 'gasts', 'gated', 'gater', 'gates', 'gator', 'gauds', 'gaudy', 'gauge', 'gault', 'gaums', 'gaunt', 'gaurs', 'gauss', 'gauze', 'gauzy', 'gavel', 'gavot', 'gawks', 'gawky', 'gawps', 'gawsy', 'gayal', 'gayer', 'gayly', 'gazar', 'gazed', 'gazer', 'gazes', 'gazoo', 'gears', 'gecko', 'gecks', 'geeks', 'geeky', 'geese', 'geest', 'gelds', 'gelee', 'gelid', 'gelts', 'gemma', 'gemmy', 'gemot', 
    'genes', 'genet', 'genic', 'genie', 'genii', 'genip', 'genoa', 'genom', 'genre', 'genro', 'gents', 'genua', 'genus', 'geode', 'geoid', 'gerah', 'germs', 'germy', 'gesso', 'geste', 'gests', 'getas', 'getup', 'geums', 'ghast', 'ghats', 'ghaut', 'ghazi', 'ghees', 'ghost', 'ghoul', 'ghyll', 'giant', 'gibed', 'giber', 'gibes', 'giddy', 'gifts', 'gigas', 'gighe', 'gigot', 'gigue', 'gilds', 'gills', 'gilly', 'gilts', 'gimel', 'gimme', 'ginks', 'ginny', 'ginzo', 'gipon', 'gipsy', 'girds', 'girls', 'girly', 'girns', 'giron', 'giros', 'girsh', 'girth', 'girts', 'gismo', 'gists', 'gites', 'given', 'giver', 'gives', 'gizmo', 'glace', 'glade', 'glads', 'glady', 'glair', 'glams', 'gland', 'glans', 'glare', 'glary', 'glass', 'glaze', 'glazy', 'gleam', 'glean', 'gleba', 'glebe', 'glede', 'gleds', 'gleed', 'gleek', 'glees', 'gleet', 'glens', 'gleys', 'glial', 'glias', 'glide', 'gliff', 
    'glime', 'glims', 'glint', 'glitz', 'gloam', 'gloat', 'globe', 'globs', 'glogg', 'gloms', 'gloom', 'glops', 'glory', 'gloss', 'glost', 'glout', 'glove', 'glows', 'gloze', 'glued', 'gluer', 'glues', 'gluey', 'glugs', 'glume', 'glums', 'gluon', 'glute', 'gluts', 'glyph', 'gnarl', 'gnarr', 'gnars', 'gnash', 'gnats', 'gnawn', 'gnaws', 'gnome', 'goads', 'goals', 'goats', 'goban', 'gobos', 'godet', 'godly', 'goers', 'gofer', 'gogos', 'going', 'golds', 'golem', 'golfs', 'golly', 'gombo', 'gomer', 'gonad', 'gonef', 'goner', 'gongs', 'gonia', 'gonif', 'gonof', 'gonzo', 'goods', 'goody', 'gooey', 'goofs', 'goofy', 'gooky', 'goons', 'goony', 'goops', 'goopy', 'goose', 'goosy', 'gopik', 'goral', 'gored', 'gores', 'gorge', 'gorms', 'gorps', 'gorse', 'gorsy', 'goths', 'gouge', 'gourd', 'gouts', 'gouty', 'gowan', 'gowds', 'gowks', 'gowns', 'goxes', 'goyim', 'graal', 'grabs', 'grace', 
    'grade', 'grads', 'graft', 'grail', 'grain', 'grama', 'gramp', 'grams', 'grana', 'grand', 'grans', 'grant', 'grape', 'graph', 'grapy', 'grasp', 'grass', 'grate', 'grave', 'gravy', 'grays', 'graze', 'great', 'grebe', 'greed', 'greek', 'green', 'grees', 'greet', 'grego', 'greys', 'gride', 'grids', 'grief', 'griff', 'grift', 'grigs', 'grill', 'grime', 'grimy', 'grind', 'grins', 'griot', 'gripe', 'grips', 'gript', 'gripy', 'grist', 'grith', 'grits', 'groan', 'groat', 'grody', 'grogs', 'groin', 'groks', 'groom', 'grope', 'gross', 'grosz', 'grots', 'group', 'grout', 'grove', 'growl', 'grown', 'grows', 'grubs', 'gruel', 'grues', 'gruff', 'grume', 'grump', 'grunt', 'guaco', 'guano', 'guans', 'guard', 'guars', 'guava', 'gucks', 'gudes', 'guess', 'guest', 'guffs', 'guide', 'guids', 'guild', 'guile', 'guilt', 'guiro', 'guise', 'gulag', 'gular', 'gulch', 'gules', 'gulfs', 'gulfy', 
    'gulls', 'gully', 'gulps', 'gulpy', 'gumbo', 'gumma', 'gummy', 'gunks', 'gunky', 'gunny', 'guppy', 'gurge', 'gurry', 'gursh', 'gurus', 'gushy', 'gussy', 'gusto', 'gusts', 'gusty', 'gutsy', 'gutta', 'gutty', 'guyed', 'guyot', 'gwine', 'gybed', 'gybes', 'gyoza', 'gypsy', 'gyral', 'gyred', 'gyres', 'gyron', 'gyros', 'gyrus', 'gyved', 'gyves', 
    
    'haafs', 'haars', 'habit', 'habus', 'hacek', 'hacks', 'hadal', 'haded', 'hades', 'hadji', 'hadst', 'haems', 'haets', 'hafis', 'hafiz', 'hafts', 'hahas', 'haika', 'haiks', 'haiku', 'hails', 'haint', 'hairs', 'hairy', 'hajes', 'hajis', 'hajji', 'hakes', 'hakim', 'hakus', 'halal', 'haled', 'haler', 'hales', 'halid', 'hallo', 'halls', 'halma', 'halms', 'halon', 'halos', 'halts', 'halva', 'halve', 'hamal', 'hames', 'hammy', 'hamza', 'hance', 'hands', 'handy', 'hangs', 'hanks', 'hanky', 'hansa', 'hanse', 'hants', 'haole', 'hapax', 'haply', 
    'happy', 'hards', 'hardy', 'hared', 'harem', 'hares', 'harks', 'harls', 'harms', 'harps', 'harpy', 'harry', 'harsh', 'harts', 'hasps', 'haste', 'hasty', 'hatch', 'hated', 'hater', 'hates', 'haugh', 'haulm', 'hauls', 'haunt', 'haute', 'haven', 'haver', 'haves', 'havoc', 'hawed', 'hawks', 'hawse', 'hayed', 'hayer', 'hayey', 'hazan', 'hazed', 'hazel', 'hazer', 'hazes', 'heads', 'heady', 'heals', 'heaps', 'heapy', 'heard', 'hears', 'heart', 'heath', 'heats', 'heave', 'heavy', 'hebes', 'hecks', 'heder', 'hedge', 'hedgy', 'heeds', 'heels', 'heeze', 'hefts', 'hefty', 'heigh', 'heils', 'heirs', 'heist', 'helio', 'helix', 'hello', 'hells', 'helms', 'helos', 'helot', 'helps', 'helve', 'hemal', 'hemes', 'hemic', 'hemin', 'hemps', 'hempy', 'hence', 'henge', 'henna', 'henry', 'hents', 'herbs', 'herby', 'herds', 'heres', 'herls', 'herma', 'herms', 'herns', 'heron', 'heros', 'herry', 
    'hertz', 'hests', 'heths', 'heuch', 'heugh', 'hewed', 'hewer', 'hexad', 'hexed', 'hexer', 'hexes', 'hexyl', 'hicks', 'hided', 'hider', 'hides', 'highs', 'hight', 'hijab', 'hijra', 'hiked', 'hiker', 'hikes', 'hilar', 'hillo', 'hills', 'hilly', 'hilts', 'hilum', 'hilus', 'hinds', 'hinge', 'hinky', 'hinny', 'hints', 'hiply', 'hippo', 'hippy', 'hired', 'hiree', 'hirer', 'hires', 'hissy', 'hists', 'hitch', 'hived', 'hives', 'hoagy', 'hoard', 'hoars', 'hoary', 'hobby', 'hobos', 'hocks', 'hocus', 'hodad', 'hoers', 'hogan', 'hoggs', 'hoick', 'hoise', 'hoist', 'hoked', 'hokes', 'hokey', 'hokku', 'hokum', 'holds', 'holed', 'holes', 'holey', 'holks', 'holla', 'hollo', 'holly', 'holms', 'holts', 'homed', 'homer', 'homes', 'homey', 'homie', 'honan', 'honda', 'honed', 'honer', 'hones', 'honey', 'hongi', 'hongs', 'honks', 'honky', 'honor', 'hooch', 'hoods', 'hoody', 'hooey', 'hoofs', 
    'hooka', 'hooks', 'hooky', 'hooly', 'hoops', 'hoots', 'hooty', 'hoped', 'hoper', 'hopes', 'hoppy', 'horah', 'horal', 'horas', 'horde', 'horns', 'horse', 'horst', 'horsy', 'hosed', 'hosel', 'hosen', 'hoser', 'hoses', 'hosey', 'hosta', 'hosts', 'hotch', 'hotel', 'hotly', 'hound', 'houri', 'hours', 'house', 'hovel', 'hover', 'howdy', 'howes', 'howff', 'howfs', 'howks', 'howls', 'hoyas', 'hoyle', 'hubby', 'hucks', 'huffs', 'huffy', 'huger', 'hulas', 'hulks', 'hulky', 'hullo', 'hulls', 'human', 'humic', 'humid', 'humor', 'humph', 'humps', 'humpy', 'humus', 'hunch', 'hunks', 'hunky', 'hunts', 'hurds', 'hurls', 'hurly', 'hurry', 'hurst', 'hurts', 'husks', 'husky', 'hussy', 'hutch', 'huzza', 'hydra', 'hydro', 'hyena', 'hying', 'hylas', 'hymen', 'hymns', 'hyoid', 'hyped', 'hyper', 'hypes', 'hypha', 'hypos', 'hyrax', 'hyson', 
    
    'iambi', 'iambs', 'ichor', 'icier', 'icily', 'icing', 'icker', 'icons', 'ictic', 'ictus', 'ideal', 'ideas', 'idiom', 'idiot', 'idled', 'idler', 'idles', 'idols', 'idyll', 'idyls', 'igged', 'igloo', 'iglus', 'ihram', 'ikats', 'ikons', 'ileac', 'ileal', 'ileum', 'ileus', 'iliac', 'iliad', 'ilial', 'ilium', 'iller', 'image', 'imago', 'imams', 'imaum', 'imbed', 'imbue', 'imide', 'imido', 'imids', 'imine', 'imino', 'immix', 'imped', 'impel', 'impis', 'imply', 'inane', 'inapt', 'inarm', 'inbox', 'inbye', 'incog', 'incur', 'incus', 'index', 'indie', 'indol', 'indow', 'indri', 'indue', 'inept', 'inert', 'infer', 'infix', 'infos', 'infra', 'ingle', 'ingot', 'inion', 'inked', 'inker', 'inkle', 'inlay', 'inlet', 'inned', 'inner', 'input', 'inrun', 'inset', 'inter', 'intis', 'intro', 'inure', 'inurn', 'invar', 'iodic', 'iodid', 'iodin', 'ionic', 'iotas', 'irade', 'irate', 'irids', 
    'iring', 'irked', 'iroko', 'irone', 'irons', 'irony', 'isbas', 'isled', 'isles', 'islet', 'issei', 'issue', 'istle', 'itchy', 'items', 'ither', 'ivied', 'ivies', 'ivory', 'ixias', 'ixora', 'ixtle', 'izars', 
    
    'jabot', 'jacal', 'jacks', 'jacky', 'jaded', 'jades', 'jager', 'jaggs', 'jaggy', 'jagra', 'jails', 'jakes', 'jalap', 'jalop', 'jambe', 'jambs', 'jammy', 'janes', 'janky', 'janty', 'japan', 'japed', 'japer', 'japes', 'jarls', 'jatos', 'jauks', 'jaunt', 'jaups', 'javas', 'jawan', 'jawed', 'jazzy', 'jeans', 'jebel', 'jeeps', 'jeers', 'jefes', 'jehad', 'jehus', 'jello', 'jells', 'jelly', 'jemmy', 'jenny', 'jerid', 'jerks', 'jerky', 'jerry', 'jesse', 'jests', 'jetes', 'jeton', 'jetty', 'jewel', 'jibbs', 'jibed', 'jiber', 'jibes', 'jiffs', 'jiffy', 'jiggy', 'jihad', 'jills', 'jilts', 'jimmy', 'jimpy', 'jingo', 'jinks', 'jinni', 'jinns', 'jisms', 'jived', 'jiver', 'jives', 'jivey', 'jnana', 'jocko', 'jocks', 'joeys', 'johns', 'joins', 'joint', 'joist', 'joked', 'joker', 'jokes', 'jokey', 'joles', 'jolly', 'jolts', 'jolty', 'jomon', 'jones', 'joram', 'jorum', 'jotas', 'jotty', 
    'joual', 'jouks', 'joule', 'joust', 'jowar', 'jowed', 'jowls', 'jowly', 'joyed', 'jubas', 'jubes', 'jucos', 'judas', 'judge', 'judos', 'jugal', 'jugum', 'juice', 'juicy', 'jujus', 'juked', 'jukes', 'jukus', 'julep', 'jumbo', 'jumps', 'jumpy', 'junco', 'junks', 'junky', 'junta', 'junto', 'jupes', 'jupon', 'jural', 'jurat', 'jurel', 'juror', 'justs', 'jutes', 'jutty', 
    
    'kabab', 'kabar', 'kabob', 'kadis', 'kafir', 'kagus', 'kaiak', 'kaifs', 'kails', 'kains', 'kakas', 'kakis', 'kalam', 'kales', 'kalif', 'kalpa', 'kames', 'kamik', 'kanas', 'kanes', 'kanji', 'kanzu', 'kaons', 'kapas', 'kaphs', 'kapok', 'kappa', 'kaput', 'karat', 'karma', 'karns', 'karoo', 'karst', 'karts', 'kasha', 'katas', 'kauri', 'kaury', 'kavas', 'kayak', 
    'kayos', 'kazoo', 'kbars', 'kebab', 'kebar', 'kebob', 'kecks', 'kedge', 'keefs', 'keeks', 'keels', 'keens', 'keeps', 'keets', 'keeve', 'kefir', 'keirs', 'kelep', 'kelim', 'kelly', 'kelps', 'kelpy', 'kelts', 'kemps', 'kempt', 'kenaf', 'kench', 'kendo', 'kenos', 'kente', 'kepis', 'kerbs', 'kerfs', 'kerne', 'kerns', 'kerry', 'ketch', 'ketol', 'kevel', 'kevil', 'kexes', 'keyed', 'khadi', 'khafs', 'khaki', 'khans', 'khaph', 'khats', 'kheda', 'kheth', 'khets', 'khoum', 'kiang', 'kibbe', 'kibbi', 'kibei', 'kibes', 'kibla', 'kicks', 'kicky', 'kiddo', 'kiddy', 'kiefs', 'kiers', 'kikes', 'kilim', 'kills', 'kilns', 'kilos', 'kilts', 'kilty', 'kinas', 'kinds', 'kines', 'kings', 'kinin', 'kinks', 'kinky', 'kinos', 'kiosk', 'kirks', 'kirns', 'kissy', 'kists', 'kited', 'kiter', 'kites', 'kithe', 'kiths', 'kitty', 'kivas', 'kiwis', 'klick', 'kliks', 'klong', 'kloof', 'kluge', 'klutz', 
    'knack', 'knaps', 'knars', 'knaur', 'knave', 'knawe', 'knead', 'kneed', 'kneel', 'knees', 'knell', 'knelt', 'knife', 'knish', 'knits', 'knobs', 'knock', 'knoll', 'knops', 'knosp', 'knots', 'knout', 'known', 'knows', 'knurl', 'knurs', 'koala', 'koans', 'kobos', 'koels', 'kohls', 'koine', 'kojis', 'kolas', 'kolos', 'kombu', 'konks', 'kooks', 'kooky', 'kopek', 'kophs', 'kopje', 'koppa', 'korai', 'koras', 'korat', 'korma', 'korun', 'kotos', 'kotow', 'kraal', 'kraft', 'krait', 'kraut', 'kreep', 'krewe', 'krill', 'krona', 'krone', 'kroon', 'krubi', 'kudos', 'kudus', 'kudzu', 'kufis', 'kugel', 'kukri', 'kulak', 'kumys', 'kurta', 'kurus', 'kusso', 'kvass', 'kvell', 'kyack', 'kyaks', 'kyars', 'kyats', 'kylix', 'kyrie', 'kytes', 'kythe'
]

const eligibleWords = ['aback', 'abase', 'abate', 'abbey', 'abbot', 'abhor', 'abide', 'abled', 'abode', 'abort', 'about', 'above', 'abuse', 'abyss', 'acorn', 'acrid', 'actor', 'acute', 'adage', 'adapt', 'adept', 'admin', 'admit', 'adobe', 'adopt', 'adore', 'adorn', 'adult', 'affix', 'afire', 'afoot', 'afoul', 'after', 'again', 'agape', 'agate', 'agent', 'agile', 'aging', 'aglow', 'agony', 'agree', 'ahead', 'aider', 'aisle', 'alarm', 'album', 'alert', 'algae', 'alibi', 'alien', 'align', 'alike', 'alive', 'allay', 'alley', 'allot', 'allow', 'alloy', 'aloft', 'alone', 'along', 'aloof', 'aloud', 'alpha', 'altar', 'alter', 'amass', 'amaze', 'amber', 'amble', 'amend', 'amiss', 'amity', 'among', 'ample', 'amply', 'amuse', 'angel', 'anger', 'angle', 'angry', 'angst', 'anime', 'ankle', 'annex', 'annoy', 'annul', 'anode', 'antic', 'anvil', 'aorta', 'apart', 'aphid', 'aping', 'apnea', 'apple', 'apply', 'apron', 'aptly', 'arbor', 'ardor', 'arena', 'argue', 'arise', 'armor', 'aroma', 'arose', 'array', 'arrow', 'arson', 'artsy', 'ascot', 'ashen', 'aside', 'askey', 'assay', 'asset', 'atoll', 'atone', 'attic', 'audio', 'audit', 'augur', 'aunty', 'avail', 'avert', 'avian', 'avoid', 'await', 'awake', 'award', 'aware', 'awash', 'awful', 'awoke', 'axial', 'axiom', 'axion', 'azure', 
        'bacon', 'badge', 'badly', 'bagel', 'baggy', 'baker', 'baler', 'balmy', 'banal', 'banjo', 'barge', 'baron', 'basal', 'basic', 'basil', 'basin', 'basis', 'baste', 'batch', 'bathe', 'baton', 'batty', 'bawdy', 'bayou', 'beach', 'beady', 'beard', 'beast', 'beech', 'beefy', 'befit', 'began', 'begat', 'beget', 'begin', 'begun', 'being', 'belch', 'belie', 'belle', 'belly', 'below', 'bench', 'beret', 'berry', 'berth', 'beset', 'betel', 'bevel', 'bezel', 'bible', 'bicep', 'biddy', 'bigot', 'bilge', 'billy', 'binge', 'bingo', 'biome', 'birch', 'birth', 'bison', 'bitty', 'black', 'blade', 'blame', 'bland', 'blank', 'blare', 'blast', 'blaze', 'bleak', 'bleat', 'bleed', 'bleep', 'blend', 'bless', 'blimp', 'blind', 'blink', 'bliss', 'blitz', 'bloat', 'block', 'bloke', 'blond', 'blood', 'bloom', 'blown', 'bluer', 'bluff', 'blunt', 'blurb', 'blurt', 'blush', 'board', 'boast', 'bobby', 'boney', 'bongo', 'bonus', 'booby', 'boost', 'booth', 'booty', 'booze', 'boozy', 'borax', 'borne', 'bosom', 'bossy', 'botch', 'bough', 'boule', 'bound', 'bowel', 'boxer', 'brace', 'braid', 'brain', 'brake', 'brand', 'brash', 'brass', 'brave', 'bravo', 'brawl', 'brawn', 'bread', 'break', 'breed', 'briar', 'bribe', 'brick', 'bride', 'brief', 'brine', 'bring', 'brink', 'briny', 'brisk', 'broad', 'broil', 'broke', 'brood', 'brook', 'broom', 'broth', 'brown', 'brunt', 'brush', 'brute', 'buddy', 'budge', 'buggy', 'bugle', 'build', 'built', 'bulge', 'bulky', 'bully', 'bunch', 'bunny', 'burly', 'burnt', 'burst', 'bused', 'bushy', 'butch', 'butte', 'buxom', 'buyer', 'bylaw', 
        'cabal', 'cabby', 'cabin', 'cable', 'cacao', 'cache', 'cacti', 'caddy', 'cadet', 'cagey', 'cairn', 'camel', 'cameo', 'canal', 'candy', 'canny', 'canoe', 'canon', 'caper', 'caput', 'carat', 'cargo', 'carol', 'carry', 'carve', 'caste', 'catch', 'cater', 'catty', 'caulk', 'cause', 'cavil', 'cease', 'cedar', 'cello', 'chafe', 'chaff', 'chain', 'chair', 'chalk', 'champ', 'chant', 'chaos', 'chard', 'charm', 'chart', 'chase', 'chasm', 'cheap', 'cheat', 'check', 'cheek', 'cheer', 'chess', 'chest', 'chick', 'chide', 'chief', 'child', 'chili', 'chill', 'chime', 'china', 'chirp', 'chock', 'choir', 'choke', 'chord', 'chore', 'chose', 'chuck', 'chump', 'chunk', 'churn', 'chute', 'cider', 'cigar', 'cinch', 'circa', 'civic', 'civil', 'clack', 'claim', 'clamp', 'clang', 'clank', 'clash', 'clasp', 'class', 'clean', 'clear', 'cleat', 'cleft', 'clerk', 'click', 'cliff', 'climb', 'cling', 'clink', 'cloak', 'clock', 'clone', 'close', 'cloth', 'cloud', 'clout', 'clove', 'clown', 'cluck', 'clued', 'clump', 'clung', 'coach', 'coast', 'cobra', 'cocoa', 'colon', 'color', 'comet', 'comfy', 'comic', 'comma', 'conch', 'condo', 'conic', 'copse', 'coral', 'corer', 'corny', 'couch', 'cough', 'could', 'count', 'coupe', 'court', 'coven', 'cover', 'covet', 'covey', 'cower', 'coyly', 'crack', 'craft', 'cramp', 'crane', 'crank', 'crash', 'crass', 'crate', 'crate', 'crave', 'crawl', 'craze', 'crazy', 'creak', 'cream', 'credo', 'creed', 'creek', 'creep', 'creme', 'crepe', 'crept', 'cress', 'crest', 'crick', 'cried', 'crier', 'crime', 'crimp', 'crisp', 'croak', 'crock', 'crone', 'crony', 'crook', 'cross', 'croup', 'crowd', 'crown', 'crude', 'cruel', 'crumb', 'crump', 'crush', 'crust', 'crypt', 'cubic', 'cumin', 'curio', 'curly', 'curry', 'curse', 'curve', 'curvy', 'cutie', 'cyber', 'cycle', 'cynic', 
        'daddy', 'daily', 'dairy', 'daisy', 'dally', 'dance', 'dandy', 'datum', 'daunt', 'dealt', 'death', 'debar', 'debit', 'debug', 'debut', 'decal', 'decay', 'decor', 'decoy', 'decry', 'defer', 'deign', 'deity', 'delay', 'delta', 'delve', 'demon', 'demur', 'denim', 'dense', 'depot', 'depth', 'derby', 'deter', 'detox', 'deuce', 'devil', 'diary', 'dicey', 'digit', 'dilly', 'dimly', 'diner', 'dingo', 'dingy', 'diode', 'dirge', 'dirty', 'disco', 'ditch', 'ditto', 'ditty', 'diver', 'dizzy', 'didge', 'dodgy', 'dogma', 'doing', 'dolly', 'donor', 'donut', 'dopey', 'doubt', 'dough', 'dowdy', 'dowel', 'downy', 'dowry', 'dozen', 'draft', 'drain', 'drake', 'drama', 'drank', 'drape', 'drawl', 'drawn', 'dread', 'dream', 'dress', 'dried', 'drier', 'drift', 'drill', 'drink', 'drive', 'droit', 'droll', 'drone', 'drool', 'droop', 'dross', 'drove', 'drown', 'druid', 'drunk', 'dryer', 'dryly', 'duchy', 'dully', 'dummy', 'dumpy', 'dunce', 'dusky', 'dusty', 'dutch', 'duvet', 'dwarf', 'dwell', 'dwelt', 'dying', 
        'eager', 'eagle', 'early', 'earth', 'easel', 'eaten', 'eater', 'ebony', 'eclat', 'edict', 'edify', 'eerie', 'egret', 'eight', 'eject', 'eking', 'elate', 'elbow', 'elder', 'elect', 'elegy', 'elfin', 'elide', 'elite', 'elope', 'elude', 'email', 'embed', 'ember', 'emcee', 'empty', 'enact', 'endow', 'enema', 'enemy', 'enjoy', 'ennui', 'ensue', 'enter', 'entry', 'envoy', 'epoch', 'epoxy', 'equal', 'equip', 'erase', 'erect', 'erode', 'error', 'erupt', 'essay', 'ester', 'ether', 'ethic', 'ethos', 'etude', 'evade', 'event', 'every', 'evict', 'evoke', 'exact', 'exalt', 'excel', 'exert', 'exile', 'exist', 'expel', 'extol', 'extra', 'exult', 'eying', 
        'fable', 'facet', 'faint', 'fairy', 'faith', 'false', 'fancy', 'fanny', 'farce', 'fatal', 'fatty', 'fault', 'fauna', 'favor', 'feast', 'fecal', 'feign', 'fella', 'felon', 'femme', 'femur', 'fence', 'feral', 'ferry', 'fetal', 'fetch', 'fetid', 'fetus', 'fever', 'fewer', 'fiber', 'ficus', 'field', 'fiend', 'fiery', 'fifth', 'fifty', 'fight', 'filer', 'filet', 'filly', 'filmy', 'filth', 'final', 'finch', 'finer', 'first', 'fishy', 'fixer', 'fizzy', 'fjord', 'flack', 'flail', 'flair', 'flake', 'flaky', 'flame', 'flank', 'flare', 'flash', 'flask', 'fleck', 'fleet', 'flesh', 'flick', 'flier', 'fling', 'flint', 'flirt', 'float', 'flock', 'flood', 'floor', 'flora', 'floss', 'flour', 'flout', 'flown', 'fluff', 'fluid', 'fluke', 'flume', 'flung', 'flunk', 'flush', 'flute', 'flyer', 'foamy', 'focal', 'focus', 'foggy', 'foist', 'folio', 'folly', 'foray', 'force', 'forge', 'forgo', 'forte', 'forth', 'forty', 'forum', 'found', 'foyer', 'frail', 'frame', 'frank', 'fraud', 'freak', 'freed', 'freer', 'fresh', 'friar', 'fried', 'frill', 'frisk', 'fritz', 'frock', 'frond', 'frond', 'front', 'frost', 'froth', 'frown', 'froze', 'fruit', 'fudge', 'fugue', 'fully', 'fungi', 'funky', 'funny', 'furor', 'furry', 'fussy', 'fuzzy', 
        'gaffe', 'gaily', 'gamer', 'gamma', 'gamut', 'gassy', 'gaudy', 'gauge', 'gaunt', 'gauze', 'gavel', 'gawky', 'gayer', 'gayly', 'gazer', 'gecko', 'geeky', 'geese', 'genie', 'genre', 'ghost', 'ghoul', 'giant', 'giddy', 'gipsy', 'girly', 'girth', 'given', 'giver', 'glade', 'gland', 'glare', 'glass', 'glaze', 'gleam', 'glean', 'glide', 'glint', 'gloat', 'globe', 'gloom', 'glory', 'gloss', 'glove', 'glyph', 'gnash', 'gnome', 'godly', 'going', 'golem', 'golly', 'gonad', 'goner', 'goody', 'gooey', 'goofy', 'goose', 'gorge', 'gouge', 'gourd', 'grace', 'grade', 'graft', 'grail', 'grain', 'grand', 'grant', 'grape', 'graph', 'grasp', 'grass', 'grate', 'grave', 'gravy', 'graze', 'great', 'greed', 'green', 'greet', 'grief', 'grill', 'grime', 'grimy', 'grind', 'gripe', 'groan', 'groin', 'groom', 'grope', 'gross', 'group', 'grout', 'grove', 'growl', 'grown', 'gruel', 'gruff', 'grunt', 'guard', 'guava', 'guess', 'guest', 'guide', 'guild', 'guile', 'guilt', 'guise', 'gulch', 'gully', 'gumbo', 'gummy', 'guppy', 'gusto', 'gusty', 'gypsy', 
        'habit', 'hairy', 'halve', 'handy', 'happy', 'hardy', 'harem', 'harpy', 'harry', 'harsh', 'haste', 'hasty', 'hatch', 'hater', 'haunt', 'haute', 'haven', 'havoc', 'hazel', 'heady', 'heard', 'heart', 'heath', 'heave', 'heavy', 'hedge', 'hefty', 'heist', 'helix', 'hello', 'hence', 'heron', 'helly', 'hinge', 'hippo', 'hippy', 'hitch', 'hoard', 'hobby', 'hoist', 'holly', 'homer', 'honey', 'honor', 'horde', 'horny', 'horse', 'hotel', 'hotly', 'hound', 'house', 'hovel', 'hover', 'howdy', 'human', 'humid', 'humor', 'humph', 'humus', 'hunch', 'hunky', 'hurry', 'husky', 'hussy', 'hutch', 'hydro', 'hyena', 'hymen', 'hyper', 
        'icily', 'icong', 'ideal', 'idiom', 'idiot', 'idler', 'idyll', 'igloo', 'iliac', 'image', 'imbue', 'impel', 'imply', 'inane', 'inbox', 'incur', 'index', 'inept', 'inert', 'infer', 'ingot', 'inlay', 'inlet', 'inner', 'input', 'inter', 'intro', 'ionic', 'irate', 'irony', 'islet', 'issue', 'itchy', 'ivory', 
        'jaunt', 'jazzy', 'helly', 'jerky', 'jetty', 'jewel', 'jiffy', 'joint', 'joist', 'joker', 'jolly', 'joust', 'judge', 'juice', 'juicy', 'jumbo', 'jumpy', 'junta', 'junto', 'juror', 
        'kappa', 'karma', 'kayak', 'kebab', 'khaki', 'kinky', 'kiosk', 'kitty', 'knack', 'knave', 'knead', 'kneed', 'kneel', 'knelt', 'knife', 'knock', 'knoll', 'known', 'koala', 'krill', 
        'label', 'labor', 'laden', 'ladle', 'lager', 'lance', 'lanky', 'lapel', 'lapse', 'large', 'larva', 'lasso', 'latch', 'later', 'lathe', 'latte', 'laugh', 'layer', 'leach', 'leafy', 'leaky', 'leant', 'leapt', 'learn', 'lease', 'leash', 'least', 'leave', 'ledge', 'leech', 'leery', 'lefty', 'legal', 'leggy', 'lemon', 'lemur', 'leper', 'level', 'lever', 'libel', 'liege', 'light', 'liken', 'lilac', 'limbo', 'limit', 'linen', 'liner', 'lingo', 'lipid', 'lithe', 'liver', 'livid', 'llama', 'loamy', 'loath', 'lobby', 'local', 'locus', 'lodge', 'lofty', 'logic', 'login', 'loopy', 'loose', 'lorry', 'loser', 'louse', 'lousy', 'lover', 'lower', 'lowly', 'loyal', 'lucid', 'lucky', 'lumen', 'lumpy', 'lunar', 'lunch', 'lunge', 'lupus', 'lurch', 'lurid', 'lusty', 'lying', 'lymph', 'lyric', 
        'macaw', 'macho', 'macro', 'madam', 'madly', 'mafia', 'magic', 'magma', 'maize', 'major', 'maker', 'mambo', 'mamma', 'mammy', 'manga', 'mange', 'mango', 'mangy', 'mania', 'manic', 'manly', 'manor', 'maple', 'march', 'marry', 'marsh', 'mason', 'masse', 'match', 'matey', 'mauve', 'maxim', 'maybe', 'mayor', 'mealy', 'meant', 'meaty', 'mecca', 'medal', 'media', 'medic', 'melee', 'melon', 'mercy', 'merge', 'merit', 'merry', 'metal', 'meter', 'metro', 'micro', 'midge', 'midst', 'might', 'milky', 'mimic', 'mince', 'miner', 'minim', 'minor', 'minty', 'minus', 'mirth', 'miser', 'missy', 'mocha', 'modal', 'model', 'modem', 'mogul', 'moist', 'molar', 'moldy', 'money', 'month', 'moody', 'moose', 'moral', 'moron', 'morph', 'mossy', 'motel', 'motif', 'motor', 'motto', 'moult', 'mound', 'mount', 'mourn', 'mouse', 'mouth', 'mover', 'movie', 'mower', 'mucky', 'mucus', 'muddy', 'mulch', 'mummy', 'munch', 'mural', 'murky', 'mushy', 'music', 'musky', 'musty', 'myrrh', 
        'nadir', 'naive', 'nanny', 'nasal', 'nasty', 'natal', 'naval', 'navel', 'needy', 'neigh', 'nerdy', 'nerve', 'never', 'newer', 'newly', 'nicer', 'niche', 'niece', 'night', 'ninja', 'ninny', 'ninth', 'noble', 'nobly', 'noise', 'noisy', 'nomad', 'noose', 'north', 'nosey', 'notch', 'novel', 'nudge', 'nurse', 'nutty', 'nylon', 'nymph', 
        'oaken', 'obese', 'occur', 'ocean', 'octal', 'octet', 'odder', 'oddly', 'offal', 'offer', 'often', 'olden', 'older', 'olive', 'ombre', 'omega', 'onion', 'onset', 'opera', 'opine', 'opium', 'optic', 'orbit', 'order', 'organ', 'other', 'otter', 'ought', 'ounce', 'outdo', 'outdo', 'outer', 'outgo', 'ovary', 'ovate', 'overt', 'ovine', 'ovoid', 'owing', 'owner', 'oxide', 'ozone', 
        'paddy', 'pagan', 'paint', 'paler', 'palsy', 'panel', 'panic', 'pansy', 'papal', 'paper', 'parer', 'parka', 'parry', 'parse', 'party', 'pasta', 'paste', 'pasty', 'patch', 'patio', 'patsy', 'patty', 'pause', 'payee', 'payer', 'peace', 'peach', 'pearl', 'pecan', 'pedal', 'penal', 'pence', 'penne', 'penny', 'perch', 'peril', 'perky', 'pesky', 'pesto', 'petal', 'petty', 'phase', 'phone', 'phony', 'photo', 'piano', 'picky', 'piece', 'piety', 'piggy', 'pilot', 'pinch', 'piney', 'pinky', 'pinto', 'piper', 
        'quack', 'quail', 'quake', 'qualm', 'quark', 'quart', 'quash', 'quasi', 'queen', 'queer', 'quell', 'query', 'quest', 'queue', 'quick', 'quiet', 'quill', 'quilt', 'quirk', 'quite', 'quota', 'quote', 'quoth', 
        'rabbi', 'rabid', 'racer', 'radar', 'radii', 'radio', 'rainy', 'raise', 'rajah', 'rally', 'ralph', 'ramen', 'ranch', 'randy', 'range', 'rapid', 'rarer', 'raspy', 'ratio', 'ratty', 'raven', 'rayon', 'razor', 'reach', 'react', 'ready', 'realm', 'rearm', 'rebar', 'rebel', 'rebus', 'rebut', 'recap', 'recur', 'recut', 'reedy', 'refer', 'refit', 'regal', 'rehab', 'reign', 'relax', 'relay', 'relic', 'remit', 'renal', 'renew', 'repay', 'repel', 'reply', 'rerun', 'reset', 'resin', 'retch', 'retro', 'retry', 'reuse', 'revel', 'revue', 'rhino', 'rhyme', 'rider', 'ridge', 'rifle', 'right', 'rigid', 'rigor', 'rinse', 'ripen', 'riper', 'risen', 'riser', 'risky', 'rival', 'river', 'rivet', 'roach', 'roast', 'robin', 'robot', 'rocky', 'rodeo', 'roger', 'rogue', 'roomy', 'roost', 'rotor', 'rouge', 'rough', 'round', 'rouse', 'route', 'rover', 'rowdy', 'rower', 'royal', 'ruddy', 'ruder', 'rugby', 'ruler', 'rumba', 'rumor', 'rupee', 'rural', 'rusty', 
        'sadly', 'safer', 'saint', 'salad', 'sally', 'salon', 'salsa', 'salty', 'salve', 'salvo', 'sandy', 'saner', 'sappy', 'sassy', 'satin', 'satyr', 'sauce', 'saucy', 'sauna', 'saute', 'savor', 'savoy', 'savvy', 'scald', 'scale', 'scalp', 'scaly', 'scamp', 'scant', 'scare', 'scarf', 'scary', 'scene', 'scent', 'scion', 'scoff', 'scold', 'scone', 'scoop', 'scope', 'score', 'scorn', 'scour', 'scout', 'scowl', 'scram', 'scrap', 'scree', 'screw', 'scrub', 'scrum', 'scuba', 'sedan', 'seedy', 'segue', 'seize', 'semen', 'sense', 'sepia', 'serif', 'serum', 'serve', 'setup', 'seven', 'sever', 'sewer', 'shack', 'shade', 'shady', 'shaft', 'shake', 'shaky', 'shale', 'shall', 'shalt', 'shame', 'shank', 'shape', 'shard', 'share', 'shark', 'sharp', 'shave', 'shawl', 'shear', 'sheen', 'sheep', 'sheer', 'sheet', 'sheik', 'shelf', 'shell', 'shied', 'shift', 'shine', 'shiny', 'shire', 'shirk', 'shirt', 'shoal', 'shock', 'shone', 'shook', 'shoot', 'shore', 
        'shorn', 'short', 'shout', 'shove', 'shown', 'showy', 'shrew', 'shrub', 'shrug', 'shuck', 'shunt', 'shush', 'shyly', 'siege', 'sieve', 'sight', 'sigma', 'silky', 'silly', 'since', 'sinew', 'singe', 'siren', 'sissy', 'sixth', 'sixty', 'skate', 'skier', 'skiff', 'skill', 'skimp', 'skirt', 'skulk', 'skull', 'skunk', 'slack', 'slain', 'slang', 'slant', 'slash', 'slate', 'sleek', 'sleep', 'sleet', 'slept', 'slice', 'slick', 'slide', 'slime', 'slimy', 'sling', 'slink', 'sloop', 'slope', 'slosh', 'sloth', 'slump', 'slung', 'slunk', 'slurp', 'slush', 'slyly', 'smack', 'small', 'smart', 'smash', 'smear', 'smell', 'smelt', 'smile', 'smirk', 'smite', 'smith', 'smock', 'smoke', 'smoky', 'smote', 'snack', 'snail', 'snake', 'snaky', 'snare', 'snarl', 'sneak', 'sneer', 'snide', 'sniff', 'snipe', 'snoop', 'snore', 'snort', 'snout', 'snowy', 'snuck', 'snuff', 'soapy', 'sober', 'soggy', 'solar', 'solid', 'solve', 'sonar', 'sonic', 'sooth', 'sooty', 'sorry', 'sound', 'south', 'sower', 'space', 'spade', 'spank', 'spare', 'spark', 'spasm', 'spawn', 'speak', 'spear', 'speck', 'speed', 'spell', 'spelt', 'spend', 'spent', 'sperm', 'spice', 'spicy', 'spied', 'spiel', 'spike', 'spiky', 'spill', 'spilt', 'spine', 'spiny', 'spire', 'spite', 'splat', 'split', 'spoil', 'spoke', 'spoof', 'spook', 'spool', 'spoon', 'spore', 'sport', 'spout', 'spray', 'spree', 'sprig', 'spunk', 'spurn', 'spurt', 'squad', 'squat', 'squib', 'stack', 'staff', 'stage', 'staid', 'stain', 'stair', 'stake', 'stale', 'stalk', 'stall', 'stamp', 'stand', 'stank', 'stare', 'stark', 'start', 'stash', 'state', 'stave', 'stead', 'steak', 'steal', 'steam', 'steed', 'steel', 'steep', 'steer', 'stein', 'stern', 'stick', 'stiff', 'still', 'stilt', 'sting', 'stink', 'stint', 'stock', 'stoic', 'stoke', 'stole', 'stomp', 'stone', 'stony', 'stood', 'stool', 'stoop', 'store', 'stork', 'storm', 'story', 'stout', 'stove', 'strap', 'straw', 'stray', 'strip', 'strut', 'stuck', 'study', 'stuff', 'stump', 'stung', 'stunk', 'stunt', 'style', 'suave', 'sugar', 'suing', 'suite', 'sulky', 'sully', 'sumac', 'sunny', 'super', 'surer', 'surge', 'surly', 'sushi', 'swami', 'swamp', 'swarm', 'swash', 'swath', 'swear', 'sweat', 'sweep', 'sweet', 'swell', 'swept', 'swift', 'swill', 'swine', 'swing', 'swirl', 'swish', 'swoon', 'swoop', 'sword', 'swore', 'sworn', 'swung', 'synod', 'syrup', 
        'tabby', 'table', 'taboo', 'tacit', 'tacky', 'taffy', 'taint', 'taken', 'taker', 'tally', 'talon', 'tamer', 'tango', 'tangy', 'taper', 'tapir', 'tardy', 'tarot', 'taste', 'tasty', 'tatty', 'taunt', 'tawny', 'teach', 'teary', 'tease', 'teddy', 'teeth', 'tempo', 'tenet', 'tenor', 'tense', 'tenth', 'tepee', 'tepid', 'terra', 'terse', 'testy', 'thank', 'theft', 'their', 'theme', 'there', 'these', 'theta', 'thick', 'thief', 'thigh', 'thing', 'think', 'third', 'thong', 'thorn', 'those', 'three', 'threw', 'throb', 'throw', 'thrum', 'thumb', 'thump', 'thyme', 'tiara', 'tibia', 'tidal', 'tiger', 'tight', 'tilde', 'timer', 'timid', 'tipsy', 'titan', 'tithe', 'title', 'toast', 'today', 'toddy', 'token', 'tonal', 'tonga', 'tonic', 'tooth', 'topaz', 'topic', 'torch', 'torso', 'torus', 'total', 'totem', 'touch', 'tough', 'towel', 'tower', 'toxic', 'toxin', 'trace', 'track', 'tract', 'trade', 'trail', 'train', 'trait', 'tramp', 'trash', 'trawl', 'tread', 'treat', 'trend', 'triad', 'trial', 'tribe', 'trice', 'trick', 'tried', 'tripe', 'trite', 'troll', 'troop', 'trope', 'trout', 'trove', 'truce', 'truck', 'truer', 'truly', 'trump', 'trunk', 'truss', 'trust', 'truth', 'tryst', 'tubal', 'tuber', 'tulip', 'tulle', 'tumor', 'tunic', 'turbo', 'tutor', 'twang', 'tweak', 'tweed', 'tweet', 'twice', 'twine', 'twirl', 'twist', 'twixt', 'tying', 
        'udder', 'ulcer', 'ultra', 'umbra', 'uncle', 'uncut', 'under', 'undid', 'undue', 'unfed', 'unfit', 'unify', 'union', 'unite', 'unity', 'unlit', 'unmet', 'unset', 'untie', 'until', 'unwed', 'unzip', 'upper', 'upset', 'urban', 'urine', 'usage', 'usher', 'using', 'usual', 'usurp', 'utile', 'utter', 
        'vague', 'valet', 'valid', 'valor', 'value', 'valve', 'vapid', 'vapor', 'vault', 'vaunt', 'vegan', 'venom', 'venue', 'verge', 'verse', 'verso', 'verve', 'vicar', 'video', 'vigil', 'vigor', 'villa', 'vinyl', 'viola', 'viper', 'viral', 'virus', 'visit', 'visor', 'vista', 'vital', 'vivid', 'vixen', 'vocal', 'vodka', 'vogue', 'voice', 'voila', 'vomit', 'voter', 'vouch', 'vowel', 
        'vying', 'wacky', 'wafer', 'wager', 'wagon', 'waist', 'waive', 'waltz', 'warty', 'waste', 'watch', 'water', 'waver', 'waxen', 'weary', 'weave', 'wedge', 'weedy', 'weigh', 'weird', 'welch', 'welsh', 'whack', 'whale', 'wharf', 'wheat', 'wheel', 'whelp', 'where', 'which', 'whiff', 'while', 'whine', 'whiny', 'whirl', 'whisk', 'white', 'whole', 'whoop', 'whose', 'widen', 'wider', 'widow', 'width', 'wield', 'wight', 'willy', 'wimpy', 'wince', 'winch', 'windy', 'wiser', 'wispy', 'witch', 'witty', 'woken', 'woman', 'women', 'woody', 'wooer', 'wooly', 'woozy', 'wordy', 'world', 'worry', 'worse', 'worst', 'worth', 'would', 'wound', 'woven', 'wrack', 'wrath', 'wreak', 'wreck', 'wrest', 'wring', 'wrist', 'write', 'wrong', 'wrote', 'wrung', 'wryly', 
        'yacht', 'yearn', 'yeast', 'yield', 'young', 'youth', 
        'zebra', 'zesty', 'zonal'];
const greyLetters = new Set();
let enteredWords = 0;
let currentLetter = 0;
let gameActive = true;

// important: ask professor if i should make extra functions to set the colors of the boxes instead of doing it in the main code

let chosenWord = eligibleWords[parseInt(Math.random() * eligibleWords.length)].toUpperCase();

reset.addEventListener("click", function() {
    // resetting without refreshing page bcs efficiency
    for (let i = 0; i < 6; i++) {
        for (let j = 0; j < 5; j++) {
            rows[i].children[j].innerHTML = "";
            makeBlockDefault(rows[i].children[j]);
        }
    }
    greyLetters.clear();
    enteredWords = 0;
    currentLetter = 0;
    gameActive = true;
    chosenWord = eligibleWords[parseInt(Math.random() * eligibleWords.length)].toUpperCase();
    metaMessage.innerHTML = "Enter a 5-letter word";
    comment.innerHTML = commentOptions[0];
});

document.addEventListener("keydown", function(event) {
    if (!gameActive) return;
    switch (event.key.toUpperCase()) {
        case "A":
        case "B":
        case "C":
        case "D":
        case "E":
        case "F":
        case "G":
        case "H":
        case "I":
        case "J":
        case "K":
        case "L":
        case "M":
        case "N":
        case "O":
        case "P":
        case "Q":
        case "R":
        case "S":
        case "T":
        case "U":
        case "V":
        case "W":
        case "X":
        case "Y":
        case "Z":
            metaMessage.innerHTML = "Enter a 5-letter word";
            if (currentLetter == 5) {
                wiggleScreenError("Already 5 letters");
                return;
            }
            rows[enteredWords].children[currentLetter].innerHTML = event.key.toUpperCase();
            if (greyLetters.has(event.key.toUpperCase())) {
                makeBlockRed(rows[enteredWords].children[currentLetter]);
            }
            currentLetter++;
            break;

        case "BACKSPACE":
            metaMessage.innerHTML = "Enter a 5-letter word";
            if (currentLetter == 0) return;
            currentLetter--;
            rows[enteredWords].children[currentLetter].innerHTML = "";
            makeBlockDefault(rows[enteredWords].children[currentLetter]);
            break;

        case "ENTER":
            event.preventDefault();
            if (currentLetter != 5) {
                wiggleScreenError("Must enter 5 letters");
                return;
            }
            let enteredWord = rows[enteredWords].children[0].innerHTML + rows[enteredWords].children[1].innerHTML + rows[enteredWords].children[2].innerHTML + rows[enteredWords].children[3].innerHTML + rows[enteredWords].children[4].innerHTML;
            if (!eligibleWords.includes(enteredWord.toLowerCase())) {
                wiggleScreenError("Entered word not in dictionary");
                return;
            }
            enteredWords++;
            currentLetter = 0;
            comment.innerHTML = commentOptions[enteredWords];

            if (enteredWord == chosenWord) {
                // win
                for (let i = 0; i < 5; i++) {
                    makeBlockGreen(rows[enteredWords - 1].children[i]);
                    toggleGameActive();
                    comment.innerHTML = "Congratulations! You guessed the word!";
                    metaMessage.innerHTML = "Click reset to play again.";
                    
                }
            } else {
                // grade
                for (let i = 0; i < 5; i++) {
                    if (enteredWord[i] == chosenWord[i]) {
                        makeBlockGreen(rows[enteredWords - 1].children[i]);
                    } else if (chosenWord.includes(enteredWord[i])) {
                        makeBlockYellow(rows[enteredWords - 1].children[i]);
                    } else {
                        makeBlockGrey(rows[enteredWords - 1].children[i]);
                        greyLetters.add(enteredWord[i]);
                    }
                }
                markDuplicateYellowsAsGrey(enteredWord);
            }
            
            if (enteredWords == 6) {
                metaMessage.innerHTML = "The word was " + chosenWord + ". Click reset to play again.";
                toggleGameActive();
            }
            break;
    }
});

function wiggleScreenError(strErrorMessage) {
    let id = null;
    let max = 20;
    let currentPos = 0;
    let rounds = 0;

    id = setInterval(() => {
        if (currentPos != max) {
            currentPos += 10 * max < 0 ? -1 : 1;
            gameboard.style.transform = "translate(" + currentPos + "px)";
        } else {
            if (max == 0) clearInterval(id);
            max *= -1;
            rounds++;
            if (rounds >= 4) max = 0;
        }
    }, 1);
    metaMessage.innerHTML = strErrorMessage;
}

function toggleGameActive() {
    gameActive = !gameActive;
}

function markDuplicateYellowsAsGrey(enteredWord) {
    let letterMaxAppearanceMap = new Map();
    let enteredLetterAppearanceMap = new Map();
    for (let i = 0; i < 5; i++) {
        if (!letterMaxAppearanceMap.has(chosenWord[i])) letterMaxAppearanceMap.set(chosenWord[i], 1);
        else letterMaxAppearanceMap.set(chosenWord[i], letterMaxAppearanceMap.get(chosenWord[i]) + 1);
        enteredLetterAppearanceMap.set(enteredWord[i], 0);
    }

    for (let i = 0; i < 5; i++) {
        if (enteredWord[i] == chosenWord[i]) {
            letterMaxAppearanceMap.set(chosenWord[i], letterMaxAppearanceMap.get(chosenWord[i]) - 1);
        }
    }

    for (let i = 0; i < 5; i++) {
        if (enteredLetterAppearanceMap.get(enteredWord[i]) >= letterMaxAppearanceMap.get(enteredWord[i]) && enteredWord[i] != chosenWord[i]) {
            makeBlockGrey(rows[enteredWords - 1].children[i]);
        } else {
            enteredLetterAppearanceMap.set(enteredWord[i], enteredLetterAppearanceMap.get(enteredWord[i]) + 1);
        }
    }
}

function makeBlockYellow(block) {
    block.style.backgroundColor = "#e5e500";
    block.style.color = "white";
    block.style.borderColor = "yellow";
}

function makeBlockGreen(block) {
    block.style.backgroundColor = "#04cc4a";
    block.style.color = "white";
    block.style.borderColor = "green";
}

function makeBlockGrey(block) {
    block.style.backgroundColor = "#888888";
    block.style.color = "white";
    block.style.borderColor = "gray";
}

function makeBlockDefault(block) {
    block.style.backgroundColor = "gainsboro";
    block.style.color = "black";
    block.style.borderColor = "grey";
}

function makeBlockRed(block) {
    block.style.backgroundColor = "red";
    block.style.color = "white";
    block.style.borderColor = "darkred";
}